os: linux
language: php

php:
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - app/vendor

install: composer install

script:
  - app/vendor/bin/php-cs-fixer fix --diff --dry-run
  - app/vendor/bin/psalm
  - app/vendor/bin/phpunit --coverage-text

before_deploy: make artifacts

deploy:
  on:
    tags: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  draft: true
  file:
    - artifacts/DirectoryLister-${TRAVIS_TAG}.tar.gz
    - artifacts/DirectoryLister-${TRAVIS_TAG}.zip
  skip_cleanup: true
